"""empty message

Revision ID: 06ec50e5d3b6
Revises: 
Create Date: 2021-04-01 11:19:45.778544

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06ec50e5d3b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Exercise', sa.Column('user_uuid', postgresql.UUID(as_uuid=True), nullable=True))
    op.create_foreign_key(None, 'Exercise', 'User', ['user_uuid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Exercise', type_='foreignkey')
    op.drop_column('Exercise', 'user_uuid')
    # ### end Alembic commands ###
